apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task1-ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /health
  namespace: task1
spec:
  rules:
    - host: sa.homework
      http:
        paths:
          - path: /back
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
          - path: /front
            pathType: Prefix
            backend:
              service:
                name: front-service
                port:
                  number: 8080
